export const OIS_DATA = {
  products: [
    {
      id: "essential-tee-offwhite",
      name: "Be humble",
      colorName: "Off-White",
      price: 1000,
      collection: "essentials",
      colorway: "cream",
      images: [
        "images/products/tshirtfront.jpg",
        "images/products/tshirtback.jpg",
      ],
      shopierUrl: "https://www.shopier.com/oissportswear/41810065",
      sizes: ["S", "M", "L", "XL"],
      soldOut: [],
      details: "240 gsm heavyweight cotton. Oversized fit. Drop shoulder. Ribbed crew neck. \"Be humble — respect the journey\" chest print. Pre-washed for drape.",
      care: "Machine wash cold, inside out. Line dry. Do not bleach.",
      ship: "Ücretsiz kargo — 2–3 iş günü içinde İstanbul'dan gönderilir.",
    },
    {
      id: "essential-hoodie-white",
      name: "It's my first time on earth",
      colorName: "White",
      price: 2000,
      collection: "essentials",
      colorway: "cream",
      images: [
        "images/products/white-front.png",
        "images/products/white-back.png",
      ],
      shopierUrl: "https://www.shopier.com/oissportswear/41769391",
      sizes: ["S", "M", "L", "XL"],
      soldOut: [],
      details: "320 gsm heavyweight loopback cotton. Oversized fit. Rib-knit cuffs and hem. Brushed interior. Pre-washed for drape.",
      care: "Machine wash cold, inside out. Line dry. Do not bleach.",
      ship: "Ücretsiz kargo — 2–3 iş günü içinde İstanbul'dan gönderilir.",
    },
    {
      id: "essential-hoodie-black",
      name: "I am only human",
      colorName: "Black",
      price: 2000,
      collection: "essentials",
      colorway: "ink",
      images: [
        "images/products/black-front.png",
        "images/products/black-back.png",
      ],
      shopierUrl: "https://www.shopier.com/oissportswear/41810332",
      sizes: ["S", "M", "L", "XL"],
      soldOut: [],
      details: "320 gsm heavyweight loopback cotton. Oversized fit. Pigment-dyed for depth. Pre-washed for drape.",
      care: "Machine wash cold, inside out. Line dry.",
      ship: "Ücretsiz kargo — 2–3 iş günü içinde İstanbul'dan gönderilir.",
    },
  ],
  collections: [],
  drops: [],
};
